### ISSUE TITLE
Empty Point Cloud

### ISSUE THREAD

**Issue by huangjy-pku** [crockwell/Cap3D#10]
Hello, thanks for the release of Cap3D data. However, in `Cap3D_pcs_pt`, I found an empty point cloud named `8d9f1798a7cb413cbb0c5ffee15ed54d.pt`. Can you help check this?

**Comment by tiangeluo** [comment]
Hi @huangjy-pku ,

Thank you very much for your feedback! 

It is indeed size 0, and I've regenerated this file. For your convenience, I uploaded to https://ltg-webaccess-files.s3.us-east-2.amazonaws.com/8d9f1798a7cb413cbb0c5ffee15ed54d.pt. You can directly replace with this one. 

I scanned all the `.pt` file and found only this particular file is size 0. I'll re-zip and update the zip file at huggingface. 

Thanks!

**Comment by huangjy-pku** [comment]
Thanks. A kind reminder: the point cloud file at your link [https://ltg-webaccess-files.s3.us-east-2.amazonaws.com/8d9f1798a7cb413cbb0c5ffee15ed54d.pt.](https://ltg-webaccess-files.s3.us-east-2.amazonaws.com/8d9f1798a7cb413cbb0c5ffee15ed54d.pt.) is at a shape of (6, 1024) instead of (6, 16384). Maybe you mistakenly take the tensor after downsampling.

**Comment by tiangeluo** [comment]
Hi Jiangyong,

Thank you! Yeah, I wrongly put the downsampled version. It was updated! 

https://ltg-webaccess-files.s3.us-east-2.amazonaws.com/8d9f1798a7cb413cbb0c5ffee15ed54d.pt
