### ISSUE TITLE
EOFError encountered

### ISSUE THREAD

**Issue by czy20000902** [crockwell/Cap3D#13]
Hello, I encountered `EOFError: Ran out of input` when using Cap3D for training. The dataloader worked well in the beginning, but crashed halfway. I've checked the caption file `Cap3D_automated_Objaverse.csv` and the data folder `Cap3D_pcs_pt` and ensured that the length of both is `661577`. The dataset integrity should be fine as well as I downloaded it from [https://huggingface.co/datasets/tiange/Cap3D/](https://huggingface.co/datasets/tiange/Cap3D/). 

The original traceback is as below:
```
Original Traceback (most recent call last):
  File "/home/chenz0f/anaconda3/envs/a100/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/chenz0f/anaconda3/envs/a100/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chenz0f/anaconda3/envs/a100/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chenz0f/X-Decoder-0918/datasets/cap3d_objverse.py", line 33, in __getitem__
    points = torch.load(self.pc_list[index])
  File "/home/chenz0f/anaconda3/envs/a100/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/chenz0f/anaconda3/envs/a100/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by tiangeluo** [comment]
hi @czy20000902 , thank you for bringing this up! I am actively working on this issue.

Could you please place a `try except` for `points = torch.load(self.pc_list[index])` and re-run the program to help locate the possible bad data?

**Comment by czy20000902** [comment]
It seems the possible bad data should be the one with uid: `d9bc2d668de14b5bb9b621b2681be6fc `and caption: `3D model of a flint arrowhead resembling a large ice shard.`. I can locate the corresponding .pt file in the dataset folder so I think maybe its content is corrupted.

**Comment by tiangeluo** [comment]
Thanks, @czy20000902 . I am looking into that specific file right now. 

Btw, because skipping few corrupted files would not harm model performance, you can add the logic into your dataloader that once faced errors re-load another obj-caption pair.

**Comment by tiangeluo** [comment]
Hi @czy20000902 , 

I redownload the data from https://huggingface.co/datasets/tiange/Cap3D/resolve/main/PointCloud_pt_zips/compressed_pcs_pt_02.zip, unzip it, and try `torch.load('./Cap3D_pcs_pt/d9bc2d668de14b5bb9b621b2681be6fc.pt'). The file was loaded successfully. 

The error should not be caused by this file. Or your download is uncompleted which yield the issue.

**Comment by czy20000902** [comment]
You are right, I got the file wrong. Sorry for the mistake, I just ran the codes again and it should be the one with uid: `8d9f1798a7cb413cbb0c5ffee15ed54d`. The code `points = torch.load('./Cap3D_pcs_pt/8d9f1798a7cb413cbb0c5ffee15ed54d.pt')` returned `EOFError: Ran out of input`
`

**Comment by tiangeluo** [comment]
Hi @czy20000902 ,

I just redownloaded https://huggingface.co/datasets/tiange/Cap3D/resolve/main/PointCloud_pt_zips/compressed_pcs_pt_00.zip and loaded `torch.load('./Cap3D_pcs_pt/8d9f1798a7cb413cbb0c5ffee15ed54d.pt')` successfully. 

The file size for `compressed_pcs_pt_00.zip` in my server is `43992826047`.  Could you please re-check your download function?

**Comment by czy20000902** [comment]
I redownloaded `compressed_pcs_pt_00.zip` and this time the size is `43992826047` as you said, the problem should be solved. Thank you very much for your help, have a nice day!

**Comment by czy20000902** [comment]
Hello, may I ask the number of classes in this dataset? I only saw the paper mentioned "Objaverse features roughly 800k 3D object assets across 21k classes". Do you have the exact value of num classes?

**Comment by tiangeluo** [comment]
Hi @czy20000902 , I do not have the exact value of num classes as the semantic class for such diverse 3D objects is hard to tell. One object can correspond to multiple semantic classes. 

If you want to calculate, I recommend you to use a image-based classifier working on rendered images. The info provided by Objaverse api is not completed and accurate, which may yield inaccurate estimation.
