### ISSUE TITLE
the blender can not load lots of glb

### ISSUE THREAD

**Issue by No360201** [crockwell/Cap3D#14]
<img width="927" alt="截屏2023-10-26 20 14 03" src="https://github.com/crockwell/Cap3D/assets/57511687/d8d6b8d2-6f36-4e7f-a3e4-6b51075440fe">

this file blender-3.4.1-linux-x64/3.4/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py
line164，unique_indices, inv_indices = np.unique(indices, return_inverse=True) is wrong

**Comment by tiangeluo** [comment]
Hi @No360201 , have you tried the blender we provided? https://huggingface.co/datasets/tiange/Cap3D/resolve/main/blender.zip 

We've tested it in our different servers, and it works well.

**Comment by crockwell** [comment]
Closing per inactivity -- feel free to open if there are further questions on this topic!
