### ISSUE TITLE
Scaling the CLIP Score

### ISSUE THREAD

**Issue by AndreAmaduzzi** [crockwell/Cap3D#16]
Hello,
I am wondering which is the meaning of the scaling by 2.5 which is applied to the CLIP Score in [this file](https://github.com/crockwell/Cap3D/blob/main/text-to-3D/evaluate.py).

Thanks in advance,
Andrea

**Comment by crockwell** [comment]
Hi Andrea,

Agreed this is a bit surprising practice, but it is [standard practice](https://arxiv.org/pdf/2104.08718.pdf). I think the reasoning is it causes values to approximately have 100 as max score.

Best,
Chris

**Comment by AndreAmaduzzi** [comment]
I see. Thanks! I will take a look at that paper.

Best,
Andrea
