### ISSUE TITLE
BLIP-2 model used for captioning

### ISSUE THREAD

**Issue by AndreAmaduzzi** [crockwell/Cap3D#17]
Hello, thanks for your interesting work.
In Section 4.2 of your research paper, you are mentioning captions generated by Cap3D in its captioning setup or by Cap3D in its VQA setup. I am wondering which BLIP-2 model you used to obtain such captions in the captioning setup (no VQA). 
Have you used the finetuned BLIP-2 for captioning **_"caption_coco_flant5xl"_** or the original xxl model **_"pretrain_flant5xxl"_** without input prompt?

By looking at **[this file](https://github.com/crockwell/Cap3D/blob/main/captioning_pipeline/caption_blip2.py#L13)**, it looks like you used the original model pretrain_flant5xxl for both the setups...

Thanks in advance,
Andrea

**Comment by crockwell** [comment]
Hi Andrea,

You are correct -- we use pretrain_flant5xxl in both setups.

Best,
Chris

**Comment by AndreAmaduzzi** [comment]
Ok! Thank you very much.

Best,
Andrea
