### ISSUE TITLE
CLIP model used for computation of CLIPScore

### ISSUE THREAD

**Issue by AndreAmaduzzi** [crockwell/Cap3D#19]
Hello! Thanks for your work. I found it very interesting.
I have a question regarding the CLIP model you used for the computation of the CLIP-Score evaluation metric.
In Section 5.1 of your main paper, you claim you have used ViT-B/16 CLIP model, to reduce bias (since you used ViT-B/32 in your pipeline).
However, in your evaluation code [here](https://github.com/crockwell/Cap3D/blob/main/text-to-3D/evaluate.py#L98), I see the CLIP model ViT-B/32.
I am wondering if I am looking at the correct code and if you can explain which model you have actually used for the evaluation of the generated captions.

Thanks,
Andrea

**Comment by crockwell** [comment]
Hi Andrea,

Good question! So we indeed used ViT-B/16 CLIP, but we used it to evaluate 3D captioning vs. crowdsourced and other captioning baselines. For text-to-3D, we use ViT-B/32 (although this is not explicitly clarified in the text). The code on this repo is for text-to-3D evaluation, so please use ViT-B/32 to be consistent with our reported results.

Best,
Chris

**Comment by AndreAmaduzzi** [comment]
Hi Chris! Thanks for your response. Indeed, I realized that the code you provided in your repo is for the evaluation of text-to-3D models.

Thanks again,
Andrea
