### ISSUE TITLE
How to evaluate the generated captions

### ISSUE THREAD

**Issue by iris0329** [crockwell/Cap3D#20]
Hi, thanks for opensourcing this repo.

I wonder how you evaluated the generated captions.
Maybe I missed some parts, but I did not find the related code.

**Comment by crockwell** [comment]
Hello, 

Good question! Unfortunately, we did not release code to evaluate captions. That being said, we used CLIP Score and CLIP R-Precision we use in [text-to-3D evaluation](https://github.com/crockwell/Cap3D/tree/main/text-to-3D#evaluation). If you read the details of the paper, you can probably replicate some of it by modifying the text-to-3D eval code!

Best of luck!
Chris

**Comment by iris0329** [comment]
Ah, I see, Thanks for sharing this ideas. I will have a detailed look at this referenced code

**Comment by iris0329** [comment]
Ah, I see, Thanks for sharing this ideas. I will have a detailed look at this referenced code

**Comment by crockwell** [comment]
Closing this issue -- feel free to open if there are further questions on this topic!
