### ISSUE TITLE
About finetuned text-to-3d model ckpt

### ISSUE THREAD

**Issue by wooseok-song** [crockwell/Cap3D#23]
Hi, thanks for great work! 

Currently, im trying to download finetuned text to 3d model ckpt from the link in this repo(huggingface), but the link doesn't exist.

Is there anyway i can download finetuned checkpoints??

thanks!

**Comment by tiangeluo** [comment]
Hi @wooseok-song , 

Thank you for your interests! The new link would be https://huggingface.co/datasets/tiange/Cap3D/tree/main/misc/our_finetuned_models, where I moved the directory a bit. Also, some newer finetuned models will be update soon.

**Comment by wooseok-song** [comment]
Thanks!
And are you planning to update finetuned image-to-3D(shape-E) checkpoint as well?
