### ISSUE TITLE
Reproducing metadata json files

### ISSUE THREAD

**Issue by yunusskeete** [crockwell/Cap3D#28]
I am looking to reproduce the rendering and captioning from Cap3D with different data and want to stay consistent with the schema and metadata that you use. The metadata provided includes origin, field of view and xyz coordinates ([example from huggingface](https://huggingface.co/datasets/tiange/Cap3D/raw/main/RenderedImage_perobj_zips/example_zipfile/00000.json)). I have not been able to identify a script which yields all of this information (field of view etc. fields missing) from any of the Cap3D, Objaverse or ABO repos. Could you release the script that you used to generate this metadata file?

**Comment by tiangeluo** [comment]
Hey @yunusskeete , thank you for your interests.

Could you please first check https://huggingface.co/datasets/tiange/Cap3D/blob/main/RenderedImage_perobj_zips/README.md, where I list the code script for saving those information?

Please let me know if you need further assistance after reading the README.

**Comment by yunusskeete** [comment]
Thanks @tiangeluo - the README is comprehensive.
